### ISSUE TITLE
无法分析

### ISSUE THREAD

**Issue by David5un** [intbjw/webshell-decryptor#1]
报错了：
Traceback (most recent call last):
  File "F:\kali32\tools\webshell-decryptor\gui.py", line 182, in run_analysis
    pcapRead(pcapName.get(), url_str.get(), key_str.get(), script_type.get(), 'aes')
  File "F:\kali32\tools\webshell-decryptor\util\pcapReader.py", line 38, in pcapRead
    pcapData = pyshark.FileCapture(
  File "D:\Python310\lib\site-packages\pyshark\capture\file_capture.py", line 38, in __init__
    super(FileCapture, self).__init__(display_filter=display_filter, only_summaries=only_summaries,
  File "D:\Python310\lib\site-packages\pyshark\capture\capture.py", line 88, in __init__
    self._setup_eventloop()
  File "D:\Python310\lib\site-packages\pyshark\capture\capture.py", line 170, in _setup_eventloop
    current_eventloop = asyncio.get_event_loop_policy().get_event_loop()
  File "D:\Python310\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (run_analysis)'.

![image](https://github.com/user-attachments/assets/45d31fac-79c8-4429-8390-6ace4d078053)

**Comment by intbjw** [comment]
好的收到，重新运行下看看还有其他报错吗，程序会闪退吗

**Comment by lutherping** [comment]
我也是遇到一楼的问题

**Comment by freefishboy** [comment]
加一，程序没闪退，cmd报线程池错
